<?php

/**
 * @file
 * Contains commerce_quickbooks_enterprise.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\commerce_quickbooks_enterprise\Event\UserEvent;
use Drupal\commerce_quickbooks_enterprise\Event\UserEvents;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_help().
 */
function commerce_quickbooks_enterprise_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_quickbooks_enterprise module.
    case 'help.page.commerce_quickbooks_enterprise':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal to Quickbooks Enterprise editions via SOAP service') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 *
 * The QBXML theme templates.
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function commerce_quickbooks_enterprise_theme($existing, $type, $theme, $path) {
  return array(
    'add_customer_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'add_inventory_product_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'add_invoice_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'add_non_inventory_product_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'add_payment_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'add_sales_receipt_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'mod_invoice_qbxml' => array(
      'variables' => array('properties' => NULL),
    ),
    'commerce_quickbooks_enterprise_qwc' => array(
      'variables' => array('properties' => NULL),
    ),
  );
}

/**
 * Implements hook_entity_base_field_info().
 *
 * @TODO: Does this need to move to hook_install?
 *
 * Attaches relevant quickbooks IDs to entities in Drupal for faster processing.
 *
 * @param \Drupal\Core\Entity\EntityTypeInterface $entity_type
 */
function commerce_quickbooks_enterprise_entity_base_field_info(EntityTypeInterface $entity_type) {
  $types = ['user', 'commerce_order', 'commerce_product_variation'];
  $entity_id = $entity_type->id();

  if (in_array($entity_id, $types)) {
    $fields['commerce_qbe_qbid'] = BaseFieldDefinition::create('text')
      ->setLabel(t('Quickbooks List ID'))
      ->setDescription(t('An ID stored in Quickbooks that references this entity.'));

    if ($entity_id == 'commerce_order') {
      $fields['commerce_qbe_edit_sequence'] = BaseFieldDefinition::create('text')
        ->setLabel(t('Quickbooks Revision ID'))
        ->setDescription(t('If this order exists on Quickbooks, in order to push updates Drupal must have the same revision ID as Quickbooks.'));
    }

    return $fields;
  }
}

/**
 * Implements hook_ENTITY_TYPE_create().
 *
 * Dispatches a commerce_quickbooks_enterprise.user.create event.
 *
 * We trigger an event instead of manually throwing the user into the Queue to
 * follow the rest of the event subscription architecture that this module
 * relies on.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function commerce_quickbooks_enterprise_user_create(\Drupal\Core\Entity\EntityInterface $entity) {
  commerce_quickbooks_enterprise_dispatch_user_event($entity, "USER_CREATE");
}

/**
 * Implement hook_ENTITY_TYPE_insert().
 *
 * Dispatches a commerce_quickbooks_enterprise.user.insert event.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function commerce_quickbooks_enterprise_user_insert(Drupal\Core\Entity\EntityInterface $entity) {
  commerce_quickbooks_enterprise_dispatch_user_event($entity, "USER_INSERT");
}

/**
 * Implement hook_ENTITY_TYPE_update().
 *
 * Dispatches a commerce_quickbooks_enterprise.user.update event.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function commerce_quickbooks_enterprise_user_update(Drupal\Core\Entity\EntityInterface $entity) {
  commerce_quickbooks_enterprise_dispatch_user_event($entity, "USER_UPDATE");
}

/**
 * Dispatches a User Event.
 *
 * Acts as a helper function for various hook_ENTITY_TYPE_* functions so that
 * they don't all need to instantiate a dispatcher and dispatch an event.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   A user entity.
 * @param $trigger
 *   The event type to trigger.
 */
function commerce_quickbooks_enterprise_dispatch_user_event(Drupal\Core\Entity\EntityInterface $entity, $trigger) {
  $dispatcher = \Drupal::service('event_dispatcher');

  $event = new UserEvent($entity);

  $dispatcher->dispatch(constant("UserEvents::$trigger"), $event);
}
